const app           = require('express')()
const compression   = require('compression')
const helmet        = require('helmet')
// const Db = require('./models/')
// const db = new Db()
app.use(helmet())
app.use(compression())
app.listen(3000, () => {
    console.log('PORT: http://localhost:3000')
})