version: "3"

services:

  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run srv-dev

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: matcha
      MYSQL_USER: rbejot
      MYSQL_PASSWORD: rbejot
    restart: always
    volumes:
      - ./data/db:/data/db