exports.register        = require('./register')
exports.confirmation    = require('./confirmation')
exports.updatedPassword = require('./updatedPassword')
exports.forgotPassword  = require('./forgotPassword')
exports.updateMail      = require('./updateMail')