exports.userAccount = require('./userAccount')
exports.admin       = require('./admin')
exports.auth        = require('./auth')
exports.profil      = require('./profil')
exports.pictures    = require('./pictures')
exports.password    = require('./password')
exports.mail        = require('./mail')
exports.tags        = require('./tags')
